<<<<<<< HEAD
import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import styles from "./index.module.css";
import Link from 'next/link';

const Members = () => {
  const{data: messages, isLoading} = trpc.useQuery(["memberdash.getAll"])
  if (isLoading) return <div>Fetching members info...</div>;

  return (
    <div className="flex flex-col gap-4">
      {messages?.map((msg, index) => {
        return (
          <div key={index}>
            <h1>{msg.name}</h1>
            <h2> {msg.batch}</h2>
          </div>
        );
      })}
    </div>
  );      
}

const Home: NextPage = () => {

  return (
    <>
    <Members/>
    <h2>
        <Link href="/dashboard">dashboard</Link>
      </h2>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.containerOuter}>
        <div className={styles.containerInner}>
          <h1 className={styles.title}>
            Create <span className={styles.titlePink}>T3</span> App
          </h1>

          <h3 className={styles.subtitle}>This stack uses:</h3>
          <div className={styles.cardGrid}>
            <TechnologyCard
              name="NextJS"
              description="The React framework for production"
              documentation="https://nextjs.org/"
            />
            <TechnologyCard
              name="TypeScript"
              description="Strongly typed programming language that builds on JavaScript, giving you better tooling at any scale"
              documentation="https://www.typescriptlang.org/"
            />
            <TechnologyCard
              name="TailwindCSS"
              description="Rapidly build modern websites without ever leaving your HTML"
              documentation="https://tailwindcss.com/"
            />
            <TechnologyCard
              name="tRPC"
              description="End-to-end typesafe APIs made easy"
              documentation="https://trpc.io/"
            />
            <TechnologyCard
              name="Next-Auth"
              description="Authentication for Next.js"
              documentation="https://next-auth.js.org/"
            />
            <TechnologyCard
              name="Prisma"
              description="Build data-driven JavaScript & TypeScript apps in less time"
              documentation="https://www.prisma.io/docs/"
            />
          </div>


=======
import type { NextPage } from 'next'
import Image from 'next/image'
import { signIn, signOut, useSession } from 'next-auth/react'

const Home: NextPage = () => {
  const { data: session } = useSession()

  return (
    <>
      <div className="bg-black text-white h-screen">
        {/* NavBar */}
        <nav className="md:flex md:items-center md:justify-between w-full">
          <span className="cursor-pointer">
            <Image
              alt="Fintech Logo"
              className="inline"
              height={82}
              src="/fintech_logo_final-removebg_white.png"
              width={188}
            />
          </span>
        </nav>

        {/* HomePage */}
        <div className="flex flex-col-reverse md:flex-row bg-black">
          <div className="flex flex-col font=[inter] ml-8">
            <div className="font-semibold text-6xl mb-8">
              <div>NUS</div>
              <div className="underline decoration-[#97AEFF] decoration-8">
                Fintech Society
              </div>
              <div className="mt-2 mb-2 text-2xl">
                Ideate. Innovate. Inspire
              </div>
            </div>
            {session ? (
              <button
                className="bg-transparent border-2 border-[#FF8A00] font-medium hover:bg-slate-800 mb-[5%] p-3 rounded text-center text-xl w-44"
                onClick={() => signOut()}
              >
                Sign Out
              </button>
            ) : (
              <button
                className="bg-transparent border-2 border-[#FF8A00] font-medium hover:bg-slate-800 mb-[5%] p-3 rounded text-center text-xl w-44"
                onClick={() => signIn()}
              >
                Sign In
              </button>
            )}
          </div>
          <Image
            alt="swe"
            className="place-items-center ml-3 mr-3"
            height={600}
            src="/undraw_software_engineer_re_tnjc.svg"
            width={600}
          />
>>>>>>> dev
        </div>
      </div>
    </>
  )
}

export default Home
